-- 1) USERS TABLE
CREATE TABLE public.users (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name      varchar(100) NOT NULL,
  last_name       varchar(100) NOT NULL,
  username        varchar(100) NOT NULL UNIQUE,
  email           varchar(200) NOT NULL UNIQUE,
  phone           varchar(50),
  password_hash   text NOT NULL,
  role            varchar(10) NOT NULL CHECK (role IN ('admin', 'user')),
  zone_center_lat double precision,
  zone_center_lng double precision,
  zone_radius_m   integer,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- 2) USER_LOCATIONS TABLE (latest location per user)
CREATE TABLE public.user_locations (
  user_id     integer PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  latitude    double precision NOT NULL,
  longitude   double precision NOT NULL,
  inside_zone boolean,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- 3) ALERTS TABLE (ENTER/EXIT events)
CREATE TABLE public.alerts (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  alert_type  varchar(10) NOT NULL CHECK (alert_type IN ('enter', 'exit')),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  latitude    double precision,
  longitude   double precision
);

INSERT INTO public.users
  (first_name, last_name, username, email, phone, password_hash, role)
VALUES
  -- Admin account
  ('System', 'Admin', 'admin', 'admin@geofence.local', NULL, 'Admin123!', 'admin'),

  -- Normal users for testing (mobile app)
  ('Omar', 'Saleh', 'driver_1',  'driver1@example.com',  '70000001', 'password123', 'user'),
  ('Layla', 'Hussein', 'field_tech', 'field.tech@example.com', '70000002', 'password123', 'user'),
  ('Karim', 'Nassar', 'security', 'security@example.com', '70000003', 'password123', 'user');
